A,B=map(int,input().split())

if(A==B):
    print(1)
    print(0)
    print(1)
    print(0)
    print(1)
    print(0)
else:
    if(A>B):
            print(1)
            print(1)
            print(0)
            print(0)
            print(0)
            print(1)
    else:
        print(0)
        print(0)
        print(1)
        print(1)
        print(0)
        print(1)